#!/bin/bash

# vars for you to adjust
PICK_RANGE="1-386"
ICON_LOCATION="./icons"
ANIMATION_LENGTH=16
JUMP_HEIGHT=64
DOUBLE_FINISH_ANIMATION=false

# don't change these pls
TEMP_IMG="bulb.png"
EMPTY_IMG="transparent.png"
OUTPUT="./out"

TEMP_IMG="$OUTPUT/$TEMP_IMG"
EMPTY_IMG="$OUTPUT/$EMPTY_IMG"

if [ "$EUID" -ne 0 ]; then 
    echo "Please run as root."
    exit
fi

while [ -n "$1" ]; do
    case "$1" in
    -u) 
        UPDATE_PLY=true
        ;;
    -k) 
        KEEP_TEMP=true
        ;;
    *) 
        echo "Option $1 not recognized!"
        ;;
    esac
    shift
done

rm -rf "$OUTPUT"
mkdir -p "$OUTPUT"

# calculate parabola vars for jump
VERTEX_X=$(($ANIMATION_LENGTH / 2))
PARAB_A=$(bc -l <<< "scale=2;($JUMP_HEIGHT / ($VERTEX_X ^ 2))")

# get path of pokemon
POKE_NUM="$(shuf -i $PICK_RANGE -n 1)"
printf -v POKE_NUM "%03d" $POKE_NUM

echo $POKE_NUM
echo $POKE_NUM > "$OUTPUT/pokenum.txt"

POKE_PATH="${ICON_LOCATION}/${POKE_NUM}.png"

# resize and trim pokemon image 
magick convert "$POKE_PATH" -interpolate Nearest -filter point -background none -resize 128x128 -trim "$TEMP_IMG"

WIDTH="$(magick identify -ping -format '%w' $TEMP_IMG)"
HEIGHT="$(magick identify -ping -format '%h' $TEMP_IMG)"

# create empty canvas
magick convert -size 256x256 xc:none "$EMPTY_IMG"

((OFFSET_W = 128 - $WIDTH / 2))
((OFFSET_H = 128 - $HEIGHT / 2))

# get average color and convert it to hex
test=$(magick convert "$TEMP_IMG" -scale 1x1\! -format '%[pixel:u]' info:-)
reg=$(echo $test | grep -oP "\d+,\d+,\d+(?=,\d+)")
reg=${reg//,/" "}
HEX_COLOR=$(printf "0x%02x%02x%02x\n" $reg)

# write .plymouth theme file
cat <<EOT > "$OUTPUT/pokemon.plymouth"
[Plymouth Theme]
Name=Pokemon
Description=Theme with a jumping Pokemon $POKE_NUM sprite
ModuleName=two-step

[two-step]
ImageDir=/usr/share/plymouth/themes/pokemon
HorizontalAlignment=.5
VerticalAlignment=.75
Transition=none
TransitionDuration=0.0
BackgroundStartColor=$HEX_COLOR
BackgroundEndColor=$HEX_COLOR
EOT

# generate frames
for i in $(seq 0 $ANIMATION_LENGTH)
    do
        # calc jump pos at current frame
        C_F=$(bc <<< "((-$PARAB_A * ($i - $VERTEX_X) ^ 2) + $JUMP_HEIGHT) / 1")
        ((POS_Y = $OFFSET_H - $C_F))
        OFFSET="+${OFFSET_W}+${POS_Y}"
        printf -v fi "%04d" $i
        # put pokemon img on canvas at calculated pos
        magick composite -geometry "$OFFSET" "$TEMP_IMG" "$EMPTY_IMG" "${OUTPUT}/throbber-${fi}.png"
        cp "${OUTPUT}/throbber-${fi}.png" "${OUTPUT}/animation-${fi}.png"
        if [ "$DOUBLE_FINISH_ANIMATION" = true ]; then
            ((ni = $ANIMATION_LENGTH + $i))
            printf -v ni "%04d" $ni
            cp "${OUTPUT}/animation-${fi}.png" "${OUTPUT}/animation-${ni}.png"
        fi
    done


if [ "$KEEP_TEMP" != true ]; then
    rm "$TEMP_IMG"
fi
rm "$EMPTY_IMG"

# add other needed files
SPINNER_DIR="/usr/share/plymouth/themes/spinner/"
cp "$SPINNER_DIR/box.png" "$OUTPUT"
cp "$SPINNER_DIR/bullet.png" "$OUTPUT"
cp "$SPINNER_DIR/lock.png" "$OUTPUT"
cp "$SPINNER_DIR/entry.png" "$OUTPUT"

# copy and apply the theme if option is given
if [ "$UPDATE_PLY" != true ]; then
    exit
fi

rm -rf "/usr/share/plymouth/themes/pokemon"
cp -rf "$OUTPUT/" "/usr/share/plymouth/themes/pokemon"
rm -rf "$OUTPUT"

plymouth-set-default-theme -R pokemon
